beacon_base_description = '''
Beacon V1 Endpoint: Returns a BeaconAlleleResponse object, similar in style to the response 
generated by a Beacon V1 REST API. This is used to query Katsu and CanDIG for
variants of interest with clinical data present.
'''

beacon_allele_request_description = '''
Beacon V1 Field: Input to be specified to query the Beacon endpoint.
'''
beacon_allele_response_description = '''
Beacon V1 Field: Response received from a Beacon Query. Beacon V1 specifications are enabled, 
alongside additional clinical data in preparation for Beacon V2.
'''

beacon_error_description = '''
Beacon V1 Field: Error Code and Message populated in the event of a failed request to the 
Beacon endpoint.
'''

beacon_og_request_description = '''
Beacon V1 Field: Description of Original Request to Beacon GraphQL endpoint.
'''

beacon_individual_description = '''
Beacon V2 Extension Field: Personal Information & Clinical Data for any patients in the Katsu Database 
that carry a variant of the type requested.
'''

beacon_id_description = '''
Beacon V1 Field: Identifies the provider of the Beacon API.
'''

beacon_api_version_description = '''
Beacon V1 Field: Identifies the version of the Beacon API 
that is in use.
'''

beacon_individuals_present_description = '''
Beacon V2 Extension: Provides clinical and personal information for Variants
within the specified range with patients in Katsu.
'''

beacon_exists_description = '''
Beacon V1 Field: Specifies whether the specified variant had patients
available in the Katsu database.
'''

beacon_personal_info = '''
Beacon V2 Extension: Provides personal information on patients with variants
in the specified range.
'''

beacon_mcode = '''
Beacon V2 Extension: Provides clinical mCODE information on patients with variants
in the specified range.
'''

beacon_phenopacket = '''
Beacon V2 Extension: Provides phenopacket information on patients with variants
in the specified range.
'''

beacon_ref_name = '''
Beacon V1 Field: The name of the chromosome in which the variant is located.
'''

beacon_ref_base = '''
Beacon V1 Field: The reference base of the variant in question.
'''

beacon_alt_base = '''
Beacon V1 Field: An Alternate base of the variant in question.
'''

beacon_start_pos = '''
Beacon V1 Field: Start coordinate of the range in which to search for the variant.
'''

beacon_end_pos = '''
Beacon V1 Field: End coordinate of the range in which to search for the variant.
'''

beacon_dataset = '''
CanDIG Server Field: IDs of the CanDIG Datasets in which to search for the variants.
'''

beacon_error_code = '''
Beacon V1 Field: Error Code received if request did not go through.
'''

beacon_error_message = '''
Beacon V1 Field: Error Message received if request did not go through.
'''