beacon_base_description = '''
Returns a BeaconAlleleResponse object, similar in style to the response 
generated by a Beacon V1 REST API. This is used to query Katsu and CanDIG for
variants of interest with clinical data present.
'''

beacon_allele_request_description = '''
Input to be specified to query the Beacon endpoint.
'''
beacon_allele_response_description = '''
Response received from a Beacon Query. Beacon V1 specifications are enabled, 
alongside added clinical data in preparation for Beacon V2.
'''

beacon_error_description = '''
Error Code and Message populated in the event of a failed request to the 
Beacon endpoint.
'''

beacon_og_request_description = '''
Description of Original Request to Beacon GraphQL endpoint.
'''

beacon_individual_description = '''
Personal Information & Clinical Data for any patients in the Katsu Database 
that carry a variant of the type requested.
'''